;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;   Kernel16.inc (c) Marco K
;;   License: GPL. See file copying for details.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;% +include

include "BOOTENG.INC"     ; english system boot messages
include "BOOTCODE.INC"    ; 16 bit system boot code

include "CD.INC"          ; cdrom support

include "HDD.INC"         ; for ATA, SATA and ATAPI devices

include "PCI16.INC"

;% -include



