
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                          ;;
;;   WINDOW SKIN for Tensor OS              ;;
;;                                          ;;
;;   oldklickers@gmail.com                  ;;
;;                                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



_skinh          dq      22

_refleft        dq      0
_skinleft       dq      0
_skinleftw      dq      66

_refbase        dq      0
_skinbase       dq      66
_skinbasew      dq      10

_refoper        dq      0
_skinoper       dq      -58
_skinoperw      dq      58

_buttonCx       dq      5
_buttonCy       dq      5
_buttonCw       dq      11
_buttonCh       dq      11

_buttonMx       dq      24
_buttonMy       dq      2
_buttonMw       dq      17
_buttonMh       dq      18

_buttonPx       dq      41
_buttonPy       dq      2
_buttonPw       dq      17
_buttonPh       dq      18


defbuttoncolor    dq   0x465670  ; 364660 ; 365260
defbuttoncolor2   dq   0xc8c8c8  ; c0c0c0

_colorframe     dq      0x33465f ; 23364F ; 00365260
_colorborder    dq      0x0
_coloroutborder dq      0x0

_fileleft       db      'LEFT.RAW     '
_filebase       db      'BASE.RAW     '
_fileoper       db      'OPER.RAW     '

_skinwinw       dq      0

;

v_skinh          dq      38

v_skinleft       dq      0
v_skinleftw      dq      66

v_skinbase       dq      66
v_skinbasew      dq      10

v_skinoper       dq      -58
v_skinoperw      dq      58



